### ISSUE TITLE
Typescript Integration

### ISSUE THREAD

**Issue by supersudh** [eklemen/generate-express#22]
**Describe the solution you'd like**
Ability to select between ES6 and Typescript when generating the boilerplate.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eklemen** [comment]
Seems like a reasonable request. We will begin looking into the effort and planning out the work. Keep checking back for updates!

**Comment by eklemen** [comment]
@supersudh 
Update: Development on ts option is underway

**Comment by eklemen** [comment]
@supersudh Hey! Haven't forgotten about things here. Just been on a bit of a break since my child was born. So far Sequelize support in typescript is code complete (in PR). I will be adding the same for mongoose/mongo as well.
Unfortunately there is not a [@types package for mongojs](https://github.com/mongo-js/mongojs/issues/281), so the supported databases will just be Sequelize for SQL, and Mongo with Mongoose, or none.
CC @smaharj1 

Edit: PR is open and ready for review. Any input would be welcome.

**Comment by eklemen** [comment]
Resolved by #25 closing issue
